エラーが出る可能性があるコードは
tryの中で書いて
想定しているエラーをcatchしたら、
catch文を実行する